import type { Meal } from '@shared/meal/meal'

export const SEED_MEALS: Meal[] = [
  {
    id: 'veggie-omelette',
    name: 'Veggie omelette with feta',
    emoji: '🍳',
    mealTypes: ['Breakfast'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 15,
    servings: 2,
    ingredients: [
      { ingredientId: 'egg', amount: 4, unit: 'piece' },
      { ingredientId: 'bell-pepper', amount: 1, unit: 'piece' },
      { ingredientId: 'mushroom', amount: 100, unit: 'g' },
      { ingredientId: 'spinach', amount: 50, unit: 'g' },
      { ingredientId: 'spring-onion', amount: 1, unit: 'piece' },
      { ingredientId: 'feta', amount: 40, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'menemen',
    name: 'Menemen',
    emoji: '🍅',
    mealTypes: ['Breakfast', 'Lunch'],
    cuisine: 'turkish',
    difficulty: 'easy',
    prepMinutes: 20,
    servings: 2,
    ingredients: [
      { ingredientId: 'egg', amount: 4, unit: 'piece' },
      { ingredientId: 'tomato', amount: 3, unit: 'piece' },
      { ingredientId: 'bell-pepper', amount: 1, unit: 'piece' },
      { ingredientId: 'green-chilli', amount: 1, unit: 'piece' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'butter', amount: 15, unit: 'g' },
      { ingredientId: 'flatbread', amount: 2, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'cilbir',
    name: 'Çılbır (poached eggs on garlic yogurt)',
    emoji: '🥣',
    mealTypes: ['Breakfast'],
    cuisine: 'turkish',
    difficulty: 'easy',
    prepMinutes: 15,
    servings: 2,
    ingredients: [
      { ingredientId: 'egg', amount: 4, unit: 'piece' },
      { ingredientId: 'greek-yogurt', amount: 250, unit: 'g' },
      { ingredientId: 'garlic', amount: 1, unit: 'piece' },
      { ingredientId: 'butter', amount: 20, unit: 'g' },
      { ingredientId: 'chilli-flake', amount: 2, unit: 'g' },
      { ingredientId: 'dill', amount: 5, unit: 'g' },
      { ingredientId: 'flatbread', amount: 2, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'sucuklu-yumurta',
    name: 'Sucuk with eggs',
    emoji: '🍳',
    mealTypes: ['Breakfast'],
    cuisine: 'turkish',
    difficulty: 'easy',
    prepMinutes: 10,
    servings: 2,
    ingredients: [
      { ingredientId: 'sucuk', amount: 100, unit: 'g' },
      { ingredientId: 'egg', amount: 4, unit: 'piece' },
      { ingredientId: 'tomato', amount: 1, unit: 'piece' },
      { ingredientId: 'butter', amount: 10, unit: 'g' },
      { ingredientId: 'wholegrain-bread', amount: 2, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'nan-panir-gerdoo',
    name: 'Bread, feta & walnuts (nan-o panir-o gerdoo)',
    emoji: '🧀',
    mealTypes: ['Breakfast'],
    cuisine: 'persian',
    difficulty: 'easy',
    prepMinutes: 5,
    servings: 2,
    ingredients: [
      { ingredientId: 'flatbread', amount: 2, unit: 'piece' },
      { ingredientId: 'feta', amount: 100, unit: 'g' },
      { ingredientId: 'walnut', amount: 40, unit: 'g' },
      { ingredientId: 'cucumber', amount: 1, unit: 'piece' },
      { ingredientId: 'tomato', amount: 2, unit: 'piece' },
      { ingredientId: 'parsley', amount: 15, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'chicken-congee',
    name: 'Chicken & ginger congee',
    emoji: '🍚',
    mealTypes: ['Breakfast', 'Lunch'],
    cuisine: 'asian',
    difficulty: 'medium',
    prepMinutes: 50,
    servings: 2,
    ingredients: [
      { ingredientId: 'jasmine-rice', amount: 100, unit: 'g' },
      { ingredientId: 'chicken-breast', amount: 150, unit: 'g' },
      { ingredientId: 'ginger', amount: 10, unit: 'g' },
      { ingredientId: 'stock-cube', amount: 1, unit: 'piece' },
      { ingredientId: 'egg', amount: 2, unit: 'piece' },
      { ingredientId: 'spring-onion', amount: 2, unit: 'piece' },
      { ingredientId: 'soy-sauce', amount: 15, unit: 'ml' },
    ],
    source: 'seed',
  },
  {
    id: 'khagineh-khorma',
    name: 'Date & egg omelette (khorma-o tokhm-e morgh)',
    emoji: '🌴',
    mealTypes: ['Breakfast'],
    cuisine: 'persian',
    difficulty: 'easy',
    prepMinutes: 15,
    servings: 2,
    ingredients: [
      { ingredientId: 'date', amount: 6, unit: 'piece' },
      { ingredientId: 'egg', amount: 4, unit: 'piece' },
      { ingredientId: 'butter', amount: 15, unit: 'g' },
      { ingredientId: 'cinnamon', amount: 1, unit: 'g' },
      { ingredientId: 'flatbread', amount: 2, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'blueberry-oatmeal',
    name: 'Blueberry banana oatmeal',
    emoji: '🥣',
    mealTypes: ['Breakfast'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 10,
    servings: 2,
    ingredients: [
      { ingredientId: 'oatmeal', amount: 100, unit: 'g' },
      { ingredientId: 'milk', amount: 400, unit: 'ml' },
      { ingredientId: 'blueberry', amount: 100, unit: 'g' },
      { ingredientId: 'banana', amount: 1, unit: 'piece' },
      { ingredientId: 'almond', amount: 20, unit: 'g' },
      { ingredientId: 'honey', amount: 15, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'strawberry-chia-overnight-oats',
    name: 'Strawberry chia overnight oats',
    emoji: '🍓',
    mealTypes: ['Breakfast'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 10,
    servings: 2,
    ingredients: [
      { ingredientId: 'oatmeal', amount: 80, unit: 'g' },
      { ingredientId: 'chia-seed', amount: 20, unit: 'g' },
      { ingredientId: 'milk', amount: 300, unit: 'ml' },
      { ingredientId: 'greek-yogurt', amount: 150, unit: 'g' },
      { ingredientId: 'strawberry', amount: 150, unit: 'g' },
      { ingredientId: 'honey', amount: 10, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'greek-yogurt-apple-walnut',
    name: 'Greek yogurt with apple, walnuts & honey',
    emoji: '🍎',
    mealTypes: ['Breakfast'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 5,
    servings: 2,
    ingredients: [
      { ingredientId: 'greek-yogurt', amount: 400, unit: 'g' },
      { ingredientId: 'apple', amount: 1, unit: 'piece' },
      { ingredientId: 'walnut', amount: 30, unit: 'g' },
      { ingredientId: 'honey', amount: 15, unit: 'g' },
      { ingredientId: 'cinnamon', amount: 1, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'avocado-egg-toast',
    name: 'Avocado toast with poached eggs',
    emoji: '🥑',
    mealTypes: ['Breakfast'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 15,
    servings: 2,
    ingredients: [
      { ingredientId: 'wholegrain-bread', amount: 4, unit: 'piece' },
      { ingredientId: 'avocado', amount: 1, unit: 'piece' },
      { ingredientId: 'egg', amount: 2, unit: 'piece' },
      { ingredientId: 'cherry-tomato', amount: 100, unit: 'g' },
      { ingredientId: 'lemon', amount: 0.5, unit: 'piece' },
      { ingredientId: 'chilli-flake', amount: 1, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'banana-oat-pancakes',
    name: 'Banana oat pancakes',
    emoji: '🥞',
    mealTypes: ['Breakfast'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 20,
    servings: 2,
    ingredients: [
      { ingredientId: 'banana', amount: 2, unit: 'piece' },
      { ingredientId: 'egg', amount: 3, unit: 'piece' },
      { ingredientId: 'oatmeal', amount: 80, unit: 'g' },
      { ingredientId: 'milk', amount: 50, unit: 'ml' },
      { ingredientId: 'blueberry', amount: 80, unit: 'g' },
      { ingredientId: 'honey', amount: 15, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'breakfast-burrito',
    name: 'Egg & black bean breakfast burrito',
    emoji: '🌯',
    mealTypes: ['Breakfast', 'Lunch'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 20,
    servings: 2,
    ingredients: [
      { ingredientId: 'tortilla-wrap', amount: 2, unit: 'piece' },
      { ingredientId: 'egg', amount: 4, unit: 'piece' },
      { ingredientId: 'black-bean', amount: 120, unit: 'g' },
      { ingredientId: 'bell-pepper', amount: 1, unit: 'piece' },
      { ingredientId: 'gouda', amount: 40, unit: 'g' },
      { ingredientId: 'salsa', amount: 60, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'cottage-cheese-tomato-toast',
    name: 'Cottage cheese & tomato toast',
    emoji: '🍞',
    mealTypes: ['Breakfast'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 10,
    servings: 2,
    ingredients: [
      { ingredientId: 'wholegrain-bread', amount: 4, unit: 'piece' },
      { ingredientId: 'cottage-cheese', amount: 200, unit: 'g' },
      { ingredientId: 'cherry-tomato', amount: 150, unit: 'g' },
      { ingredientId: 'cucumber', amount: 0.5, unit: 'piece' },
      { ingredientId: 'dill', amount: 5, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'tofu-scramble',
    name: 'Tofu scramble with spinach',
    emoji: '🥬',
    mealTypes: ['Breakfast'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 15,
    servings: 2,
    ingredients: [
      { ingredientId: 'tofu', amount: 300, unit: 'g' },
      { ingredientId: 'spinach', amount: 80, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'cherry-tomato', amount: 100, unit: 'g' },
      { ingredientId: 'turmeric', amount: 2, unit: 'g' },
      { ingredientId: 'wholegrain-bread', amount: 2, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'tamagoyaki',
    name: 'Tamagoyaki (Japanese rolled omelette)',
    emoji: '🥚',
    mealTypes: ['Breakfast'],
    cuisine: 'asian',
    difficulty: 'medium',
    prepMinutes: 20,
    servings: 2,
    ingredients: [
      { ingredientId: 'egg', amount: 5, unit: 'piece' },
      { ingredientId: 'soy-sauce', amount: 10, unit: 'ml' },
      { ingredientId: 'sugar', amount: 10, unit: 'g' },
      { ingredientId: 'spring-onion', amount: 1, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'uitsmijter',
    name: 'Uitsmijter (fried eggs, ham & cheese on bread)',
    emoji: '🍳',
    mealTypes: ['Breakfast', 'Lunch'],
    cuisine: 'dutch',
    difficulty: 'easy',
    prepMinutes: 10,
    servings: 2,
    ingredients: [
      { ingredientId: 'wholegrain-bread', amount: 4, unit: 'piece' },
      { ingredientId: 'egg', amount: 4, unit: 'piece' },
      { ingredientId: 'turkey-ham', amount: 80, unit: 'g' },
      { ingredientId: 'gouda', amount: 60, unit: 'g' },
      { ingredientId: 'tomato', amount: 1, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'dutch-apple-pancakes',
    name: 'Dutch apple pancakes (appelpannenkoeken)',
    emoji: '🥞',
    mealTypes: ['Breakfast', 'Lunch'],
    cuisine: 'dutch',
    difficulty: 'easy',
    prepMinutes: 30,
    servings: 2,
    ingredients: [
      { ingredientId: 'flour', amount: 150, unit: 'g' },
      { ingredientId: 'milk', amount: 300, unit: 'ml' },
      { ingredientId: 'egg', amount: 2, unit: 'piece' },
      { ingredientId: 'apple', amount: 1, unit: 'piece' },
      { ingredientId: 'butter', amount: 20, unit: 'g' },
      { ingredientId: 'cinnamon', amount: 1, unit: 'g' },
      { ingredientId: 'sugar', amount: 15, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'gozleme-spinach-feta',
    name: 'Gözleme with spinach & feta',
    emoji: '🫓',
    mealTypes: ['Breakfast', 'Lunch'],
    cuisine: 'turkish',
    difficulty: 'medium',
    prepMinutes: 40,
    servings: 2,
    ingredients: [
      { ingredientId: 'flour', amount: 250, unit: 'g' },
      { ingredientId: 'yogurt', amount: 100, unit: 'g' },
      { ingredientId: 'spinach', amount: 150, unit: 'g' },
      { ingredientId: 'feta', amount: 120, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'butter', amount: 20, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'peanut-butter-banana-toast',
    name: 'Peanut butter banana toast',
    emoji: '🍌',
    mealTypes: ['Breakfast'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 5,
    servings: 2,
    ingredients: [
      { ingredientId: 'wholegrain-bread', amount: 4, unit: 'piece' },
      { ingredientId: 'peanut-butter', amount: 40, unit: 'g' },
      { ingredientId: 'banana', amount: 2, unit: 'piece' },
      { ingredientId: 'chia-seed', amount: 10, unit: 'g' },
      { ingredientId: 'honey', amount: 10, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'adas-polo',
    name: 'Adas polo (lentil rice with raisins & dates)',
    emoji: '🍚',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'medium',
    prepMinutes: 60,
    servings: 2,
    ingredients: [
      { ingredientId: 'basmati-rice', amount: 200, unit: 'g' },
      { ingredientId: 'green-lentil', amount: 100, unit: 'g' },
      { ingredientId: 'beef-mince', amount: 200, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'raisin', amount: 50, unit: 'g' },
      { ingredientId: 'date', amount: 6, unit: 'piece' },
      { ingredientId: 'advieh', amount: 3, unit: 'g' },
      { ingredientId: 'saffron', amount: 0.2, unit: 'g' },
      { ingredientId: 'butter', amount: 20, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'kabab-tabei',
    name: 'Kabab tabei (pan kebab) with rice',
    emoji: '🍢',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'easy',
    prepMinutes: 30,
    servings: 2,
    ingredients: [
      { ingredientId: 'beef-mince', amount: 350, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'turmeric', amount: 1, unit: 'g' },
      { ingredientId: 'tomato', amount: 2, unit: 'piece' },
      { ingredientId: 'basmati-rice', amount: 200, unit: 'g' },
      { ingredientId: 'saffron', amount: 0.2, unit: 'g' },
      { ingredientId: 'sumac', amount: 2, unit: 'g' },
      { ingredientId: 'butter', amount: 15, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'sabzi-polo-mahi',
    name: 'Sabzi polo ba mahi (herb rice with fish)',
    emoji: '🐟',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'medium',
    prepMinutes: 50,
    servings: 2,
    ingredients: [
      { ingredientId: 'basmati-rice', amount: 200, unit: 'g' },
      { ingredientId: 'cod-fillet', amount: 350, unit: 'g' },
      { ingredientId: 'dill', amount: 30, unit: 'g' },
      { ingredientId: 'parsley', amount: 30, unit: 'g' },
      { ingredientId: 'fresh-coriander', amount: 20, unit: 'g' },
      { ingredientId: 'chive', amount: 20, unit: 'g' },
      { ingredientId: 'garlic', amount: 2, unit: 'piece' },
      { ingredientId: 'turmeric', amount: 2, unit: 'g' },
      { ingredientId: 'lemon', amount: 1, unit: 'piece' },
      { ingredientId: 'butter', amount: 20, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'adasi',
    name: 'Adasi (Persian lentil stew)',
    emoji: '🥣',
    mealTypes: ['Dinner'],
    cuisine: 'persian',
    difficulty: 'easy',
    prepMinutes: 45,
    servings: 2,
    ingredients: [
      { ingredientId: 'green-lentil', amount: 200, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'potato', amount: 150, unit: 'g' },
      { ingredientId: 'turmeric', amount: 2, unit: 'g' },
      { ingredientId: 'cumin', amount: 2, unit: 'g' },
      { ingredientId: 'butter', amount: 15, unit: 'g' },
      { ingredientId: 'flatbread', amount: 2, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'ghormeh-sabzi',
    name: 'Ghormeh sabzi',
    emoji: '🌿',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'hard',
    prepMinutes: 180,
    servings: 2,
    ingredients: [
      { ingredientId: 'lamb-stew-meat', amount: 300, unit: 'g' },
      { ingredientId: 'kidney-bean', amount: 150, unit: 'g' },
      { ingredientId: 'parsley', amount: 100, unit: 'g' },
      { ingredientId: 'fresh-coriander', amount: 50, unit: 'g' },
      { ingredientId: 'chive', amount: 50, unit: 'g' },
      { ingredientId: 'dried-fenugreek', amount: 10, unit: 'g' },
      { ingredientId: 'dried-lime', amount: 3, unit: 'piece' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'turmeric', amount: 2, unit: 'g' },
      { ingredientId: 'basmati-rice', amount: 200, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'ash-reshteh',
    name: 'Ash reshteh',
    emoji: '🍲',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'hard',
    prepMinutes: 150,
    servings: 2,
    ingredients: [
      { ingredientId: 'reshteh', amount: 100, unit: 'g' },
      { ingredientId: 'chickpea', amount: 80, unit: 'g' },
      { ingredientId: 'kidney-bean', amount: 80, unit: 'g' },
      { ingredientId: 'green-lentil', amount: 60, unit: 'g' },
      { ingredientId: 'spinach', amount: 150, unit: 'g' },
      { ingredientId: 'parsley', amount: 50, unit: 'g' },
      { ingredientId: 'fresh-coriander', amount: 30, unit: 'g' },
      { ingredientId: 'kashk', amount: 100, unit: 'ml' },
      { ingredientId: 'onion', amount: 2, unit: 'piece' },
      { ingredientId: 'dried-mint', amount: 5, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'gheymeh',
    name: 'Gheymeh (split pea stew with fries)',
    emoji: '🍛',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'medium',
    prepMinutes: 90,
    servings: 2,
    ingredients: [
      { ingredientId: 'beef-stew-meat', amount: 300, unit: 'g' },
      { ingredientId: 'yellow-split-pea', amount: 80, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'tomato-paste', amount: 30, unit: 'g' },
      { ingredientId: 'dried-lime', amount: 2, unit: 'piece' },
      { ingredientId: 'potato', amount: 250, unit: 'g' },
      { ingredientId: 'turmeric', amount: 2, unit: 'g' },
      { ingredientId: 'cinnamon', amount: 1, unit: 'g' },
      { ingredientId: 'basmati-rice', amount: 200, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'kuku-sabzi',
    name: 'Kuku sabzi (herb frittata)',
    emoji: '🥬',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'easy',
    prepMinutes: 40,
    servings: 2,
    ingredients: [
      { ingredientId: 'egg', amount: 5, unit: 'piece' },
      { ingredientId: 'parsley', amount: 60, unit: 'g' },
      { ingredientId: 'fresh-coriander', amount: 40, unit: 'g' },
      { ingredientId: 'dill', amount: 30, unit: 'g' },
      { ingredientId: 'chive', amount: 30, unit: 'g' },
      { ingredientId: 'walnut', amount: 30, unit: 'g' },
      { ingredientId: 'flour', amount: 10, unit: 'g' },
      { ingredientId: 'turmeric', amount: 1, unit: 'g' },
      { ingredientId: 'yogurt', amount: 150, unit: 'g' },
      { ingredientId: 'flatbread', amount: 2, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'kuku-sibzamini',
    name: 'Kuku sibzamini (potato patties)',
    emoji: '🥔',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'easy',
    prepMinutes: 35,
    servings: 2,
    ingredients: [
      { ingredientId: 'potato', amount: 400, unit: 'g' },
      { ingredientId: 'egg', amount: 3, unit: 'piece' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'turmeric', amount: 1, unit: 'g' },
      { ingredientId: 'tomato', amount: 2, unit: 'piece' },
      { ingredientId: 'flatbread', amount: 2, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'joojeh-kabab',
    name: 'Joojeh kabab (saffron chicken) with rice',
    emoji: '🍗',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'easy',
    prepMinutes: 45,
    servings: 2,
    ingredients: [
      { ingredientId: 'chicken-breast', amount: 400, unit: 'g' },
      { ingredientId: 'yogurt', amount: 100, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'lemon', amount: 1, unit: 'piece' },
      { ingredientId: 'saffron', amount: 0.2, unit: 'g' },
      { ingredientId: 'butter', amount: 20, unit: 'g' },
      { ingredientId: 'tomato', amount: 2, unit: 'piece' },
      { ingredientId: 'basmati-rice', amount: 200, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'loobia-polo',
    name: 'Loobia polo (green bean rice with beef)',
    emoji: '🫛',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'easy',
    prepMinutes: 60,
    servings: 2,
    ingredients: [
      { ingredientId: 'basmati-rice', amount: 200, unit: 'g' },
      { ingredientId: 'beef-mince', amount: 250, unit: 'g' },
      { ingredientId: 'green-bean', amount: 200, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'tomato-paste', amount: 40, unit: 'g' },
      { ingredientId: 'turmeric', amount: 2, unit: 'g' },
      { ingredientId: 'cinnamon', amount: 1, unit: 'g' },
      { ingredientId: 'advieh', amount: 2, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'estamboli-polo',
    name: 'Estamboli polo (tomato & potato rice)',
    emoji: '🍅',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'easy',
    prepMinutes: 45,
    servings: 2,
    ingredients: [
      { ingredientId: 'basmati-rice', amount: 200, unit: 'g' },
      { ingredientId: 'potato', amount: 250, unit: 'g' },
      { ingredientId: 'tomato', amount: 2, unit: 'piece' },
      { ingredientId: 'tomato-paste', amount: 30, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'turmeric', amount: 2, unit: 'g' },
      { ingredientId: 'yogurt', amount: 150, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'kashk-e-bademjan',
    name: 'Kashk-e bademjan',
    emoji: '🍆',
    mealTypes: ['Dinner'],
    cuisine: 'persian',
    difficulty: 'medium',
    prepMinutes: 50,
    servings: 2,
    ingredients: [
      { ingredientId: 'aubergine', amount: 2, unit: 'piece' },
      { ingredientId: 'kashk', amount: 100, unit: 'ml' },
      { ingredientId: 'onion', amount: 2, unit: 'piece' },
      { ingredientId: 'garlic', amount: 3, unit: 'piece' },
      { ingredientId: 'walnut', amount: 30, unit: 'g' },
      { ingredientId: 'dried-mint', amount: 3, unit: 'g' },
      { ingredientId: 'turmeric', amount: 1, unit: 'g' },
      { ingredientId: 'flatbread', amount: 2, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'mirza-ghasemi',
    name: 'Mirza ghasemi (smoky aubergine & egg)',
    emoji: '🍆',
    mealTypes: ['Dinner'],
    cuisine: 'persian',
    difficulty: 'medium',
    prepMinutes: 45,
    servings: 2,
    ingredients: [
      { ingredientId: 'aubergine', amount: 2, unit: 'piece' },
      { ingredientId: 'tomato', amount: 3, unit: 'piece' },
      { ingredientId: 'garlic', amount: 4, unit: 'piece' },
      { ingredientId: 'egg', amount: 3, unit: 'piece' },
      { ingredientId: 'turmeric', amount: 1, unit: 'g' },
      { ingredientId: 'flatbread', amount: 2, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'persian-makaroni',
    name: 'Persian macaroni with tahdig',
    emoji: '🍝',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'easy',
    prepMinutes: 60,
    servings: 2,
    ingredients: [
      { ingredientId: 'macaroni', amount: 250, unit: 'g' },
      { ingredientId: 'beef-mince', amount: 250, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'tomato-paste', amount: 40, unit: 'g' },
      { ingredientId: 'bell-pepper', amount: 1, unit: 'piece' },
      { ingredientId: 'potato', amount: 200, unit: 'g' },
      { ingredientId: 'turmeric', amount: 2, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'kotlet',
    name: 'Kotlet (beef & potato patties)',
    emoji: '🥔',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'medium',
    prepMinutes: 45,
    servings: 2,
    ingredients: [
      { ingredientId: 'beef-mince', amount: 300, unit: 'g' },
      { ingredientId: 'potato', amount: 300, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'egg', amount: 1, unit: 'piece' },
      { ingredientId: 'breadcrumb', amount: 40, unit: 'g' },
      { ingredientId: 'turmeric', amount: 1, unit: 'g' },
      { ingredientId: 'tomato', amount: 2, unit: 'piece' },
      { ingredientId: 'flatbread', amount: 2, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'khoresh-bademjan',
    name: 'Khoresh bademjan (aubergine & beef stew)',
    emoji: '🍛',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'medium',
    prepMinutes: 90,
    servings: 2,
    ingredients: [
      { ingredientId: 'beef-stew-meat', amount: 300, unit: 'g' },
      { ingredientId: 'aubergine', amount: 2, unit: 'piece' },
      { ingredientId: 'tomato', amount: 2, unit: 'piece' },
      { ingredientId: 'tomato-paste', amount: 30, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'lemon', amount: 0.5, unit: 'piece' },
      { ingredientId: 'turmeric', amount: 2, unit: 'g' },
      { ingredientId: 'saffron', amount: 0.1, unit: 'g' },
      { ingredientId: 'basmati-rice', amount: 200, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'chelo-morgh',
    name: 'Chelo morgh (saffron braised chicken with rice)',
    emoji: '🍗',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'easy',
    prepMinutes: 60,
    servings: 2,
    ingredients: [
      { ingredientId: 'chicken-thigh', amount: 500, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'tomato-paste', amount: 15, unit: 'g' },
      { ingredientId: 'lemon', amount: 1, unit: 'piece' },
      { ingredientId: 'saffron', amount: 0.2, unit: 'g' },
      { ingredientId: 'turmeric', amount: 2, unit: 'g' },
      { ingredientId: 'basmati-rice', amount: 200, unit: 'g' },
      { ingredientId: 'butter', amount: 20, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'olivieh-sandwich',
    name: 'Olivieh (chicken potato salad) sandwich',
    emoji: '🥪',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'medium',
    prepMinutes: 60,
    servings: 2,
    ingredients: [
      { ingredientId: 'chicken-breast', amount: 250, unit: 'g' },
      { ingredientId: 'potato', amount: 400, unit: 'g' },
      { ingredientId: 'egg', amount: 3, unit: 'piece' },
      { ingredientId: 'green-pea', amount: 100, unit: 'g' },
      { ingredientId: 'carrot', amount: 1, unit: 'piece' },
      { ingredientId: 'mayonnaise', amount: 120, unit: 'g' },
      { ingredientId: 'lemon', amount: 0.5, unit: 'piece' },
      { ingredientId: 'bread-roll', amount: 2, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'havij-polo',
    name: 'Havij polo (carrot rice with chicken)',
    emoji: '🥕',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'medium',
    prepMinutes: 60,
    servings: 2,
    ingredients: [
      { ingredientId: 'basmati-rice', amount: 200, unit: 'g' },
      { ingredientId: 'chicken-breast', amount: 300, unit: 'g' },
      { ingredientId: 'carrot', amount: 3, unit: 'piece' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'saffron', amount: 0.2, unit: 'g' },
      { ingredientId: 'sugar', amount: 10, unit: 'g' },
      { ingredientId: 'cinnamon', amount: 1, unit: 'g' },
      { ingredientId: 'advieh', amount: 2, unit: 'g' },
      { ingredientId: 'butter', amount: 20, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'abgoosht',
    name: 'Abgoosht (lamb & chickpea stew)',
    emoji: '🍲',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'hard',
    prepMinutes: 180,
    servings: 2,
    ingredients: [
      { ingredientId: 'lamb-stew-meat', amount: 350, unit: 'g' },
      { ingredientId: 'chickpea', amount: 80, unit: 'g' },
      { ingredientId: 'kidney-bean', amount: 60, unit: 'g' },
      { ingredientId: 'potato', amount: 250, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'tomato', amount: 2, unit: 'piece' },
      { ingredientId: 'tomato-paste', amount: 20, unit: 'g' },
      { ingredientId: 'dried-lime', amount: 2, unit: 'piece' },
      { ingredientId: 'turmeric', amount: 2, unit: 'g' },
      { ingredientId: 'flatbread', amount: 2, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'shami-lappeh',
    name: 'Shami lappeh (split pea & beef patties)',
    emoji: '🥙',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'medium',
    prepMinutes: 60,
    servings: 2,
    ingredients: [
      { ingredientId: 'yellow-split-pea', amount: 100, unit: 'g' },
      { ingredientId: 'beef-mince', amount: 250, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'egg', amount: 1, unit: 'piece' },
      { ingredientId: 'turmeric', amount: 2, unit: 'g' },
      { ingredientId: 'advieh', amount: 2, unit: 'g' },
      { ingredientId: 'tomato', amount: 2, unit: 'piece' },
      { ingredientId: 'flatbread', amount: 2, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'tahchin',
    name: 'Tahchin (saffron rice cake with chicken)',
    emoji: '🍚',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'hard',
    prepMinutes: 120,
    servings: 2,
    ingredients: [
      { ingredientId: 'basmati-rice', amount: 200, unit: 'g' },
      { ingredientId: 'chicken-breast', amount: 300, unit: 'g' },
      { ingredientId: 'yogurt', amount: 200, unit: 'g' },
      { ingredientId: 'egg', amount: 2, unit: 'piece' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'saffron', amount: 0.3, unit: 'g' },
      { ingredientId: 'turmeric', amount: 1, unit: 'g' },
      { ingredientId: 'butter', amount: 30, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'soup-e-morgh',
    name: 'Soup-e morgh (Persian chicken & vegetable soup)',
    emoji: '🍜',
    mealTypes: ['Dinner'],
    cuisine: 'persian',
    difficulty: 'easy',
    prepMinutes: 45,
    servings: 2,
    ingredients: [
      { ingredientId: 'chicken-breast', amount: 250, unit: 'g' },
      { ingredientId: 'carrot', amount: 2, unit: 'piece' },
      { ingredientId: 'potato', amount: 200, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'egg-noodle', amount: 50, unit: 'g' },
      { ingredientId: 'lemon', amount: 1, unit: 'piece' },
      { ingredientId: 'parsley', amount: 15, unit: 'g' },
      { ingredientId: 'turmeric', amount: 1, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'dopiazeh-aloo',
    name: 'Dopiazeh aloo (potato, onion & lamb)',
    emoji: '🧅',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'easy',
    prepMinutes: 40,
    servings: 2,
    ingredients: [
      { ingredientId: 'potato', amount: 400, unit: 'g' },
      { ingredientId: 'onion', amount: 2, unit: 'piece' },
      { ingredientId: 'lamb-mince', amount: 200, unit: 'g' },
      { ingredientId: 'tomato-paste', amount: 30, unit: 'g' },
      { ingredientId: 'turmeric', amount: 2, unit: 'g' },
      { ingredientId: 'dried-mint', amount: 2, unit: 'g' },
      { ingredientId: 'flatbread', amount: 2, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'dolmeh-felfel',
    name: 'Dolmeh felfel (stuffed peppers)',
    emoji: '🫑',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'persian',
    difficulty: 'medium',
    prepMinutes: 75,
    servings: 2,
    ingredients: [
      { ingredientId: 'bell-pepper', amount: 4, unit: 'piece' },
      { ingredientId: 'beef-mince', amount: 200, unit: 'g' },
      { ingredientId: 'basmati-rice', amount: 80, unit: 'g' },
      { ingredientId: 'yellow-split-pea', amount: 30, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'parsley', amount: 20, unit: 'g' },
      { ingredientId: 'dill', amount: 10, unit: 'g' },
      { ingredientId: 'tomato-paste', amount: 30, unit: 'g' },
      { ingredientId: 'lemon', amount: 0.5, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'mercimek-corbasi',
    name: 'Mercimek çorbası (red lentil soup)',
    emoji: '🥣',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'turkish',
    difficulty: 'easy',
    prepMinutes: 35,
    servings: 2,
    ingredients: [
      { ingredientId: 'red-lentil', amount: 150, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'carrot', amount: 1, unit: 'piece' },
      { ingredientId: 'potato', amount: 100, unit: 'g' },
      { ingredientId: 'tomato-paste', amount: 15, unit: 'g' },
      { ingredientId: 'butter', amount: 20, unit: 'g' },
      { ingredientId: 'cumin', amount: 2, unit: 'g' },
      { ingredientId: 'paprika', amount: 2, unit: 'g' },
      { ingredientId: 'dried-mint', amount: 2, unit: 'g' },
      { ingredientId: 'lemon', amount: 1, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'tavuk-sis',
    name: 'Tavuk şiş (chicken skewers) with bulgur pilaf',
    emoji: '🍢',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'turkish',
    difficulty: 'medium',
    prepMinutes: 45,
    servings: 2,
    ingredients: [
      { ingredientId: 'chicken-breast', amount: 400, unit: 'g' },
      { ingredientId: 'yogurt', amount: 100, unit: 'g' },
      { ingredientId: 'tomato-paste', amount: 15, unit: 'g' },
      { ingredientId: 'paprika', amount: 3, unit: 'g' },
      { ingredientId: 'garlic', amount: 2, unit: 'piece' },
      { ingredientId: 'bell-pepper', amount: 1, unit: 'piece' },
      { ingredientId: 'red-onion', amount: 1, unit: 'piece' },
      { ingredientId: 'bulgur', amount: 150, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'izgara-kofte',
    name: 'Izgara köfte (grilled meatballs)',
    emoji: '🧆',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'turkish',
    difficulty: 'easy',
    prepMinutes: 30,
    servings: 2,
    ingredients: [
      { ingredientId: 'beef-mince', amount: 250, unit: 'g' },
      { ingredientId: 'lamb-mince', amount: 150, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'breadcrumb', amount: 30, unit: 'g' },
      { ingredientId: 'cumin', amount: 2, unit: 'g' },
      { ingredientId: 'parsley', amount: 15, unit: 'g' },
      { ingredientId: 'tomato', amount: 2, unit: 'piece' },
      { ingredientId: 'green-chilli', amount: 2, unit: 'piece' },
      { ingredientId: 'flatbread', amount: 2, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'karniyarik',
    name: 'Karnıyarık (stuffed aubergine) with rice',
    emoji: '🍆',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'turkish',
    difficulty: 'medium',
    prepMinutes: 60,
    servings: 2,
    ingredients: [
      { ingredientId: 'aubergine', amount: 2, unit: 'piece' },
      { ingredientId: 'beef-mince', amount: 250, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'tomato', amount: 2, unit: 'piece' },
      { ingredientId: 'green-chilli', amount: 2, unit: 'piece' },
      { ingredientId: 'garlic', amount: 2, unit: 'piece' },
      { ingredientId: 'tomato-paste', amount: 20, unit: 'g' },
      { ingredientId: 'basmati-rice', amount: 150, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'etli-nohut',
    name: 'Etli nohut (beef & chickpea stew) with rice',
    emoji: '🫘',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'turkish',
    difficulty: 'easy',
    prepMinutes: 75,
    servings: 2,
    ingredients: [
      { ingredientId: 'beef-stew-meat', amount: 250, unit: 'g' },
      { ingredientId: 'chickpea', amount: 300, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'tomato-paste', amount: 30, unit: 'g' },
      { ingredientId: 'paprika', amount: 2, unit: 'g' },
      { ingredientId: 'butter', amount: 15, unit: 'g' },
      { ingredientId: 'basmati-rice', amount: 150, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'lahmacun',
    name: 'Lahmacun',
    emoji: '🫓',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'turkish',
    difficulty: 'medium',
    prepMinutes: 60,
    servings: 2,
    ingredients: [
      { ingredientId: 'flour', amount: 250, unit: 'g' },
      { ingredientId: 'lamb-mince', amount: 200, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'tomato', amount: 2, unit: 'piece' },
      { ingredientId: 'bell-pepper', amount: 1, unit: 'piece' },
      { ingredientId: 'tomato-paste', amount: 20, unit: 'g' },
      { ingredientId: 'parsley', amount: 20, unit: 'g' },
      { ingredientId: 'paprika', amount: 2, unit: 'g' },
      { ingredientId: 'lemon', amount: 1, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'manti',
    name: 'Mantı (dumplings with garlic yogurt)',
    emoji: '🥟',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'turkish',
    difficulty: 'hard',
    prepMinutes: 120,
    servings: 2,
    ingredients: [
      { ingredientId: 'flour', amount: 250, unit: 'g' },
      { ingredientId: 'egg', amount: 1, unit: 'piece' },
      { ingredientId: 'lamb-mince', amount: 200, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'yogurt', amount: 250, unit: 'g' },
      { ingredientId: 'garlic', amount: 2, unit: 'piece' },
      { ingredientId: 'butter', amount: 30, unit: 'g' },
      { ingredientId: 'chilli-flake', amount: 2, unit: 'g' },
      { ingredientId: 'dried-mint', amount: 2, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'tavuk-doner-wrap',
    name: 'Chicken döner wrap (tavuk dürüm)',
    emoji: '🌯',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'turkish',
    difficulty: 'easy',
    prepMinutes: 30,
    servings: 2,
    ingredients: [
      { ingredientId: 'chicken-thigh', amount: 400, unit: 'g' },
      { ingredientId: 'yogurt', amount: 100, unit: 'g' },
      { ingredientId: 'paprika', amount: 3, unit: 'g' },
      { ingredientId: 'cumin', amount: 1, unit: 'g' },
      { ingredientId: 'garlic', amount: 2, unit: 'piece' },
      { ingredientId: 'flatbread', amount: 2, unit: 'piece' },
      { ingredientId: 'lettuce', amount: 0.5, unit: 'piece' },
      { ingredientId: 'tomato', amount: 1, unit: 'piece' },
      { ingredientId: 'red-onion', amount: 1, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'balik-ekmek',
    name: 'Balık ekmek (fish sandwich)',
    emoji: '🐟',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'turkish',
    difficulty: 'easy',
    prepMinutes: 20,
    servings: 2,
    ingredients: [
      { ingredientId: 'pangasius-fillet', amount: 300, unit: 'g' },
      { ingredientId: 'bread-roll', amount: 2, unit: 'piece' },
      { ingredientId: 'lettuce', amount: 0.5, unit: 'piece' },
      { ingredientId: 'tomato', amount: 1, unit: 'piece' },
      { ingredientId: 'red-onion', amount: 1, unit: 'piece' },
      { ingredientId: 'lemon', amount: 1, unit: 'piece' },
      { ingredientId: 'sumac', amount: 2, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'tavuk-sote',
    name: 'Tavuk sote (chicken & pepper sauté) with rice',
    emoji: '🫑',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'turkish',
    difficulty: 'easy',
    prepMinutes: 30,
    servings: 2,
    ingredients: [
      { ingredientId: 'chicken-breast', amount: 400, unit: 'g' },
      { ingredientId: 'bell-pepper', amount: 2, unit: 'piece' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'tomato', amount: 2, unit: 'piece' },
      { ingredientId: 'tomato-paste', amount: 15, unit: 'g' },
      { ingredientId: 'garlic', amount: 2, unit: 'piece' },
      { ingredientId: 'paprika', amount: 2, unit: 'g' },
      { ingredientId: 'basmati-rice', amount: 150, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'broodje-gezond',
    name: 'Broodje gezond (cheese, ham & egg roll)',
    emoji: '🥪',
    mealTypes: ['Lunch'],
    cuisine: 'dutch',
    difficulty: 'easy',
    prepMinutes: 15,
    servings: 2,
    ingredients: [
      { ingredientId: 'bread-roll', amount: 2, unit: 'piece' },
      { ingredientId: 'gouda', amount: 60, unit: 'g' },
      { ingredientId: 'turkey-ham', amount: 60, unit: 'g' },
      { ingredientId: 'egg', amount: 2, unit: 'piece' },
      { ingredientId: 'tomato', amount: 1, unit: 'piece' },
      { ingredientId: 'cucumber', amount: 0.5, unit: 'piece' },
      { ingredientId: 'lettuce', amount: 0.25, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'chicken-cheese-tosti',
    name: 'Chicken & cheese tosti',
    emoji: '🧀',
    mealTypes: ['Lunch'],
    cuisine: 'dutch',
    difficulty: 'easy',
    prepMinutes: 10,
    servings: 2,
    ingredients: [
      { ingredientId: 'wholegrain-bread', amount: 4, unit: 'piece' },
      { ingredientId: 'gouda', amount: 80, unit: 'g' },
      { ingredientId: 'sliced-chicken', amount: 80, unit: 'g' },
      { ingredientId: 'ketchup', amount: 20, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'erwtensoep',
    name: 'Erwtensoep (split pea soup with turkey)',
    emoji: '🥣',
    mealTypes: ['Dinner'],
    cuisine: 'dutch',
    difficulty: 'medium',
    prepMinutes: 90,
    servings: 2,
    ingredients: [
      { ingredientId: 'yellow-split-pea', amount: 200, unit: 'g' },
      { ingredientId: 'turkey-ham', amount: 120, unit: 'g' },
      { ingredientId: 'potato', amount: 200, unit: 'g' },
      { ingredientId: 'carrot', amount: 2, unit: 'piece' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'stock-cube', amount: 1, unit: 'piece' },
      { ingredientId: 'bread-roll', amount: 2, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'hutspot-steak',
    name: 'Hutspot (carrot & potato mash) with steak',
    emoji: '🥕',
    mealTypes: ['Dinner'],
    cuisine: 'dutch',
    difficulty: 'easy',
    prepMinutes: 40,
    servings: 2,
    ingredients: [
      { ingredientId: 'potato', amount: 500, unit: 'g' },
      { ingredientId: 'carrot', amount: 3, unit: 'piece' },
      { ingredientId: 'onion', amount: 2, unit: 'piece' },
      { ingredientId: 'beef-steak', amount: 300, unit: 'g' },
      { ingredientId: 'butter', amount: 20, unit: 'g' },
      { ingredientId: 'milk', amount: 50, unit: 'ml' },
    ],
    source: 'seed',
  },
  {
    id: 'tomatensoep-balletjes',
    name: 'Tomatensoep met balletjes (tomato soup with meatballs)',
    emoji: '🍅',
    mealTypes: ['Dinner'],
    cuisine: 'dutch',
    difficulty: 'easy',
    prepMinutes: 35,
    servings: 2,
    ingredients: [
      { ingredientId: 'tinned-tomato', amount: 400, unit: 'g' },
      { ingredientId: 'beef-mince', amount: 200, unit: 'g' },
      { ingredientId: 'breadcrumb', amount: 20, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'carrot', amount: 1, unit: 'piece' },
      { ingredientId: 'stock-cube', amount: 1, unit: 'piece' },
      { ingredientId: 'bread-roll', amount: 2, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'gehaktbal-aardappelen',
    name: 'Gehaktbal with potatoes & green beans',
    emoji: '🧆',
    mealTypes: ['Dinner'],
    cuisine: 'dutch',
    difficulty: 'easy',
    prepMinutes: 45,
    servings: 2,
    ingredients: [
      { ingredientId: 'beef-mince', amount: 400, unit: 'g' },
      { ingredientId: 'egg', amount: 1, unit: 'piece' },
      { ingredientId: 'breadcrumb', amount: 40, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'potato', amount: 500, unit: 'g' },
      { ingredientId: 'green-bean', amount: 250, unit: 'g' },
      { ingredientId: 'butter', amount: 20, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'hachee',
    name: 'Hachee (beef & onion stew) with red cabbage',
    emoji: '🍲',
    mealTypes: ['Dinner'],
    cuisine: 'dutch',
    difficulty: 'medium',
    prepMinutes: 150,
    servings: 2,
    ingredients: [
      { ingredientId: 'beef-stew-meat', amount: 400, unit: 'g' },
      { ingredientId: 'onion', amount: 3, unit: 'piece' },
      { ingredientId: 'flour', amount: 15, unit: 'g' },
      { ingredientId: 'stock-cube', amount: 1, unit: 'piece' },
      { ingredientId: 'butter', amount: 20, unit: 'g' },
      { ingredientId: 'potato', amount: 500, unit: 'g' },
      { ingredientId: 'red-cabbage', amount: 250, unit: 'g' },
      { ingredientId: 'apple', amount: 1, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'chicken-teriyaki-rice',
    name: 'Chicken teriyaki with rice & broccoli',
    emoji: '🍱',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'asian',
    difficulty: 'easy',
    prepMinutes: 25,
    servings: 2,
    ingredients: [
      { ingredientId: 'chicken-thigh', amount: 400, unit: 'g' },
      { ingredientId: 'teriyaki-sauce', amount: 60, unit: 'ml' },
      { ingredientId: 'jasmine-rice', amount: 150, unit: 'g' },
      { ingredientId: 'broccoli', amount: 200, unit: 'g' },
      { ingredientId: 'spring-onion', amount: 2, unit: 'piece' },
      { ingredientId: 'sesame-seed', amount: 5, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'shrimp-fried-rice',
    name: 'Shrimp fried rice',
    emoji: '🍤',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'asian',
    difficulty: 'easy',
    prepMinutes: 20,
    servings: 2,
    ingredients: [
      { ingredientId: 'jasmine-rice', amount: 150, unit: 'g' },
      { ingredientId: 'shrimp', amount: 250, unit: 'g' },
      { ingredientId: 'egg', amount: 2, unit: 'piece' },
      { ingredientId: 'green-pea', amount: 100, unit: 'g' },
      { ingredientId: 'carrot', amount: 1, unit: 'piece' },
      { ingredientId: 'spring-onion', amount: 2, unit: 'piece' },
      { ingredientId: 'garlic', amount: 2, unit: 'piece' },
      { ingredientId: 'soy-sauce', amount: 30, unit: 'ml' },
      { ingredientId: 'sesame-oil', amount: 10, unit: 'ml' },
    ],
    source: 'seed',
  },
  {
    id: 'chicken-coconut-curry',
    name: 'Chicken coconut curry with rice',
    emoji: '🍛',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'asian',
    difficulty: 'easy',
    prepMinutes: 40,
    servings: 2,
    ingredients: [
      { ingredientId: 'chicken-breast', amount: 400, unit: 'g' },
      { ingredientId: 'coconut-milk', amount: 400, unit: 'ml' },
      { ingredientId: 'curry-powder', amount: 10, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'garlic', amount: 2, unit: 'piece' },
      { ingredientId: 'ginger', amount: 10, unit: 'g' },
      { ingredientId: 'spinach', amount: 100, unit: 'g' },
      { ingredientId: 'jasmine-rice', amount: 150, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'salmon-poke-bowl',
    name: 'Salmon poke bowl',
    emoji: '🍣',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'asian',
    difficulty: 'easy',
    prepMinutes: 25,
    servings: 2,
    ingredients: [
      { ingredientId: 'salmon-fillet', amount: 250, unit: 'g' },
      { ingredientId: 'jasmine-rice', amount: 150, unit: 'g' },
      { ingredientId: 'avocado', amount: 1, unit: 'piece' },
      { ingredientId: 'edamame', amount: 100, unit: 'g' },
      { ingredientId: 'cucumber', amount: 1, unit: 'piece' },
      { ingredientId: 'carrot', amount: 1, unit: 'piece' },
      { ingredientId: 'soy-sauce', amount: 30, unit: 'ml' },
      { ingredientId: 'sriracha', amount: 10, unit: 'ml' },
      { ingredientId: 'mayonnaise', amount: 20, unit: 'g' },
      { ingredientId: 'sesame-seed', amount: 5, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'beef-broccoli-stir-fry',
    name: 'Beef & broccoli stir-fry with rice',
    emoji: '🥦',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'asian',
    difficulty: 'easy',
    prepMinutes: 25,
    servings: 2,
    ingredients: [
      { ingredientId: 'beef-steak', amount: 350, unit: 'g' },
      { ingredientId: 'broccoli', amount: 300, unit: 'g' },
      { ingredientId: 'garlic', amount: 2, unit: 'piece' },
      { ingredientId: 'ginger', amount: 10, unit: 'g' },
      { ingredientId: 'soy-sauce', amount: 40, unit: 'ml' },
      { ingredientId: 'honey', amount: 15, unit: 'g' },
      { ingredientId: 'sesame-oil', amount: 10, unit: 'ml' },
      { ingredientId: 'jasmine-rice', amount: 150, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'chicken-satay-rice',
    name: 'Kip saté (chicken satay) with rice',
    emoji: '🥜',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'asian',
    difficulty: 'easy',
    prepMinutes: 35,
    servings: 2,
    ingredients: [
      { ingredientId: 'chicken-thigh', amount: 400, unit: 'g' },
      { ingredientId: 'peanut-butter', amount: 60, unit: 'g' },
      { ingredientId: 'coconut-milk', amount: 100, unit: 'ml' },
      { ingredientId: 'soy-sauce', amount: 30, unit: 'ml' },
      { ingredientId: 'garlic', amount: 2, unit: 'piece' },
      { ingredientId: 'lime', amount: 1, unit: 'piece' },
      { ingredientId: 'cucumber', amount: 1, unit: 'piece' },
      { ingredientId: 'jasmine-rice', amount: 150, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'chicken-chow-mein',
    name: 'Chicken chow mein',
    emoji: '🍜',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'asian',
    difficulty: 'easy',
    prepMinutes: 25,
    servings: 2,
    ingredients: [
      { ingredientId: 'egg-noodle', amount: 200, unit: 'g' },
      { ingredientId: 'chicken-breast', amount: 300, unit: 'g' },
      { ingredientId: 'bell-pepper', amount: 1, unit: 'piece' },
      { ingredientId: 'carrot', amount: 1, unit: 'piece' },
      { ingredientId: 'spring-onion', amount: 2, unit: 'piece' },
      { ingredientId: 'garlic', amount: 2, unit: 'piece' },
      { ingredientId: 'ginger', amount: 5, unit: 'g' },
      { ingredientId: 'soy-sauce', amount: 40, unit: 'ml' },
      { ingredientId: 'sesame-oil', amount: 10, unit: 'ml' },
    ],
    source: 'seed',
  },
  {
    id: 'sesame-tofu-rice-bowl',
    name: 'Sticky sesame tofu rice bowl',
    emoji: '🥢',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'asian',
    difficulty: 'easy',
    prepMinutes: 30,
    servings: 2,
    ingredients: [
      { ingredientId: 'tofu', amount: 400, unit: 'g' },
      { ingredientId: 'jasmine-rice', amount: 150, unit: 'g' },
      { ingredientId: 'edamame', amount: 100, unit: 'g' },
      { ingredientId: 'carrot', amount: 1, unit: 'piece' },
      { ingredientId: 'garlic', amount: 2, unit: 'piece' },
      { ingredientId: 'soy-sauce', amount: 30, unit: 'ml' },
      { ingredientId: 'honey', amount: 15, unit: 'g' },
      { ingredientId: 'sesame-seed', amount: 10, unit: 'g' },
      { ingredientId: 'spring-onion', amount: 2, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'bibimbap',
    name: 'Beef bibimbap',
    emoji: '🍚',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'asian',
    difficulty: 'medium',
    prepMinutes: 45,
    servings: 2,
    ingredients: [
      { ingredientId: 'jasmine-rice', amount: 150, unit: 'g' },
      { ingredientId: 'beef-mince', amount: 250, unit: 'g' },
      { ingredientId: 'spinach', amount: 150, unit: 'g' },
      { ingredientId: 'carrot', amount: 1, unit: 'piece' },
      { ingredientId: 'courgette', amount: 1, unit: 'piece' },
      { ingredientId: 'mushroom', amount: 100, unit: 'g' },
      { ingredientId: 'egg', amount: 2, unit: 'piece' },
      { ingredientId: 'soy-sauce', amount: 20, unit: 'ml' },
      { ingredientId: 'sriracha', amount: 20, unit: 'ml' },
      { ingredientId: 'sesame-oil', amount: 10, unit: 'ml' },
    ],
    source: 'seed',
  },
  {
    id: 'chicken-lettuce-wraps',
    name: 'Chicken lettuce wraps',
    emoji: '🥬',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'asian',
    difficulty: 'easy',
    prepMinutes: 20,
    servings: 2,
    ingredients: [
      { ingredientId: 'chicken-breast', amount: 350, unit: 'g' },
      { ingredientId: 'lettuce', amount: 1, unit: 'piece' },
      { ingredientId: 'carrot', amount: 1, unit: 'piece' },
      { ingredientId: 'spring-onion', amount: 2, unit: 'piece' },
      { ingredientId: 'garlic', amount: 2, unit: 'piece' },
      { ingredientId: 'ginger', amount: 5, unit: 'g' },
      { ingredientId: 'soy-sauce', amount: 30, unit: 'ml' },
      { ingredientId: 'honey', amount: 10, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'chicken-sweetcorn-soup',
    name: 'Chicken & sweetcorn soup',
    emoji: '🌽',
    mealTypes: ['Dinner'],
    cuisine: 'asian',
    difficulty: 'easy',
    prepMinutes: 25,
    servings: 2,
    ingredients: [
      { ingredientId: 'chicken-breast', amount: 200, unit: 'g' },
      { ingredientId: 'sweet-corn', amount: 200, unit: 'g' },
      { ingredientId: 'egg', amount: 2, unit: 'piece' },
      { ingredientId: 'stock-cube', amount: 1, unit: 'piece' },
      { ingredientId: 'spring-onion', amount: 2, unit: 'piece' },
      { ingredientId: 'ginger', amount: 5, unit: 'g' },
      { ingredientId: 'soy-sauce', amount: 15, unit: 'ml' },
    ],
    source: 'seed',
  },
  {
    id: 'chicken-katsu-curry',
    name: 'Chicken katsu curry',
    emoji: '🍛',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'asian',
    difficulty: 'medium',
    prepMinutes: 50,
    servings: 2,
    ingredients: [
      { ingredientId: 'chicken-breast', amount: 350, unit: 'g' },
      { ingredientId: 'flour', amount: 30, unit: 'g' },
      { ingredientId: 'egg', amount: 1, unit: 'piece' },
      { ingredientId: 'breadcrumb', amount: 80, unit: 'g' },
      { ingredientId: 'curry-powder', amount: 10, unit: 'g' },
      { ingredientId: 'carrot', amount: 1, unit: 'piece' },
      { ingredientId: 'potato', amount: 200, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'jasmine-rice', amount: 150, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'tuna-mayo-rice-bowl',
    name: 'Tuna mayo rice bowl',
    emoji: '🍙',
    mealTypes: ['Lunch'],
    cuisine: 'asian',
    difficulty: 'easy',
    prepMinutes: 15,
    servings: 2,
    ingredients: [
      { ingredientId: 'tinned-tuna', amount: 150, unit: 'g' },
      { ingredientId: 'jasmine-rice', amount: 150, unit: 'g' },
      { ingredientId: 'mayonnaise', amount: 40, unit: 'g' },
      { ingredientId: 'soy-sauce', amount: 15, unit: 'ml' },
      { ingredientId: 'cucumber', amount: 1, unit: 'piece' },
      { ingredientId: 'sweet-corn', amount: 80, unit: 'g' },
      { ingredientId: 'spring-onion', amount: 1, unit: 'piece' },
      { ingredientId: 'sesame-seed', amount: 5, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'honey-garlic-shrimp-rice',
    name: 'Honey garlic shrimp with rice',
    emoji: '🍯',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'asian',
    difficulty: 'easy',
    prepMinutes: 20,
    servings: 2,
    ingredients: [
      { ingredientId: 'shrimp', amount: 300, unit: 'g' },
      { ingredientId: 'garlic', amount: 4, unit: 'piece' },
      { ingredientId: 'honey', amount: 30, unit: 'g' },
      { ingredientId: 'soy-sauce', amount: 30, unit: 'ml' },
      { ingredientId: 'green-bean', amount: 200, unit: 'g' },
      { ingredientId: 'jasmine-rice', amount: 150, unit: 'g' },
      { ingredientId: 'sesame-seed', amount: 5, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'red-lentil-dal',
    name: 'Red lentil dal with rice',
    emoji: '🥘',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'asian',
    difficulty: 'easy',
    prepMinutes: 35,
    servings: 2,
    ingredients: [
      { ingredientId: 'red-lentil', amount: 200, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'garlic', amount: 3, unit: 'piece' },
      { ingredientId: 'ginger', amount: 10, unit: 'g' },
      { ingredientId: 'tinned-tomato', amount: 200, unit: 'g' },
      { ingredientId: 'coconut-milk', amount: 100, unit: 'ml' },
      { ingredientId: 'turmeric', amount: 2, unit: 'g' },
      { ingredientId: 'cumin', amount: 2, unit: 'g' },
      { ingredientId: 'spinach', amount: 100, unit: 'g' },
      { ingredientId: 'basmati-rice', amount: 150, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'beef-burger',
    name: 'Beef burger with sweet potato fries',
    emoji: '🍔',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 35,
    servings: 2,
    ingredients: [
      { ingredientId: 'beef-mince', amount: 350, unit: 'g' },
      { ingredientId: 'burger-bun', amount: 2, unit: 'piece' },
      { ingredientId: 'gouda', amount: 40, unit: 'g' },
      { ingredientId: 'lettuce', amount: 0.25, unit: 'piece' },
      { ingredientId: 'tomato', amount: 1, unit: 'piece' },
      { ingredientId: 'red-onion', amount: 1, unit: 'piece' },
      { ingredientId: 'ketchup', amount: 20, unit: 'g' },
      { ingredientId: 'mustard', amount: 10, unit: 'g' },
      { ingredientId: 'sweet-potato', amount: 300, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'beef-tacos',
    name: 'Beef tacos',
    emoji: '🌮',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 25,
    servings: 2,
    ingredients: [
      { ingredientId: 'beef-mince', amount: 300, unit: 'g' },
      { ingredientId: 'taco-seasoning', amount: 15, unit: 'g' },
      { ingredientId: 'tortilla-wrap', amount: 4, unit: 'piece' },
      { ingredientId: 'lettuce', amount: 0.25, unit: 'piece' },
      { ingredientId: 'tomato', amount: 1, unit: 'piece' },
      { ingredientId: 'gouda', amount: 50, unit: 'g' },
      { ingredientId: 'salsa', amount: 80, unit: 'g' },
      { ingredientId: 'greek-yogurt', amount: 60, unit: 'g' },
    ],
    source: 'seed',
  },

  {
    id: 'grilled-chicken-burger',
    name: 'Grilled chicken burger',
    emoji: '🍔',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 25,
    servings: 2,
    ingredients: [
      { ingredientId: 'chicken-breast', amount: 350, unit: 'g' },
      { ingredientId: 'burger-bun', amount: 2, unit: 'piece' },
      { ingredientId: 'paprika', amount: 2, unit: 'g' },
      { ingredientId: 'garlic', amount: 1, unit: 'piece' },
      { ingredientId: 'avocado', amount: 1, unit: 'piece' },
      { ingredientId: 'lettuce', amount: 0.25, unit: 'piece' },
      { ingredientId: 'tomato', amount: 1, unit: 'piece' },
      { ingredientId: 'mayonnaise', amount: 20, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'fish-tacos',
    name: 'Fish tacos with red cabbage slaw',
    emoji: '🌮',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 25,
    servings: 2,
    ingredients: [
      { ingredientId: 'cod-fillet', amount: 300, unit: 'g' },
      { ingredientId: 'tortilla-wrap', amount: 4, unit: 'piece' },
      { ingredientId: 'red-cabbage', amount: 150, unit: 'g' },
      { ingredientId: 'greek-yogurt', amount: 80, unit: 'g' },
      { ingredientId: 'lime', amount: 1, unit: 'piece' },
      { ingredientId: 'avocado', amount: 1, unit: 'piece' },
      { ingredientId: 'fresh-coriander', amount: 10, unit: 'g' },
      { ingredientId: 'paprika', amount: 2, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'chicken-fajita-wraps',
    name: 'Chicken fajita wraps',
    emoji: '🌯',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 25,
    servings: 2,
    ingredients: [
      { ingredientId: 'chicken-breast', amount: 350, unit: 'g' },
      { ingredientId: 'bell-pepper', amount: 2, unit: 'piece' },
      { ingredientId: 'red-onion', amount: 1, unit: 'piece' },
      { ingredientId: 'taco-seasoning', amount: 15, unit: 'g' },
      { ingredientId: 'tortilla-wrap', amount: 4, unit: 'piece' },
      { ingredientId: 'salsa', amount: 60, unit: 'g' },
      { ingredientId: 'greek-yogurt', amount: 60, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'chili-con-carne',
    name: 'Chili con carne with rice',
    emoji: '🌶️',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'international',
    difficulty: 'medium',
    prepMinutes: 50,
    servings: 2,
    ingredients: [
      { ingredientId: 'beef-mince', amount: 300, unit: 'g' },
      { ingredientId: 'kidney-bean', amount: 200, unit: 'g' },
      { ingredientId: 'tinned-tomato', amount: 400, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'bell-pepper', amount: 1, unit: 'piece' },
      { ingredientId: 'garlic', amount: 2, unit: 'piece' },
      { ingredientId: 'cumin', amount: 3, unit: 'g' },
      { ingredientId: 'paprika', amount: 3, unit: 'g' },
      { ingredientId: 'chilli-flake', amount: 1, unit: 'g' },
      { ingredientId: 'basmati-rice', amount: 150, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'spaghetti-bolognese',
    name: 'Spaghetti bolognese',
    emoji: '🍝',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 40,
    servings: 2,
    ingredients: [
      { ingredientId: 'spaghetti', amount: 200, unit: 'g' },
      { ingredientId: 'beef-mince', amount: 300, unit: 'g' },
      { ingredientId: 'tinned-tomato', amount: 400, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'carrot', amount: 1, unit: 'piece' },
      { ingredientId: 'garlic', amount: 2, unit: 'piece' },
      { ingredientId: 'oregano', amount: 2, unit: 'g' },
      { ingredientId: 'parmesan', amount: 30, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'chicken-caesar-salad',
    name: 'Chicken Caesar-style salad',
    emoji: '🥗',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 25,
    servings: 2,
    ingredients: [
      { ingredientId: 'chicken-breast', amount: 300, unit: 'g' },
      { ingredientId: 'lettuce', amount: 1, unit: 'piece' },
      { ingredientId: 'parmesan', amount: 30, unit: 'g' },
      { ingredientId: 'wholegrain-bread', amount: 2, unit: 'piece' },
      { ingredientId: 'mayonnaise', amount: 40, unit: 'g' },
      { ingredientId: 'lemon', amount: 0.5, unit: 'piece' },
      { ingredientId: 'garlic', amount: 1, unit: 'piece' },
      { ingredientId: 'mustard', amount: 5, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'tuna-salad-sandwich',
    name: 'Tuna salad sandwich',
    emoji: '🥪',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 10,
    servings: 2,
    ingredients: [
      { ingredientId: 'tinned-tuna', amount: 150, unit: 'g' },
      { ingredientId: 'wholegrain-bread', amount: 4, unit: 'piece' },
      { ingredientId: 'greek-yogurt', amount: 40, unit: 'g' },
      { ingredientId: 'mayonnaise', amount: 20, unit: 'g' },
      { ingredientId: 'red-onion', amount: 0.5, unit: 'piece' },
      { ingredientId: 'sweet-corn', amount: 60, unit: 'g' },
      { ingredientId: 'lettuce', amount: 0.25, unit: 'piece' },
      { ingredientId: 'tomato', amount: 1, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'honey-mustard-salmon',
    name: 'Honey mustard salmon with sweet potato & broccoli',
    emoji: '🐟',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 35,
    servings: 2,
    ingredients: [
      { ingredientId: 'salmon-fillet', amount: 300, unit: 'g' },
      { ingredientId: 'honey', amount: 15, unit: 'g' },
      { ingredientId: 'mustard', amount: 15, unit: 'g' },
      { ingredientId: 'sweet-potato', amount: 400, unit: 'g' },
      { ingredientId: 'broccoli', amount: 250, unit: 'g' },
      { ingredientId: 'lemon', amount: 0.5, unit: 'piece' },
      { ingredientId: 'garlic', amount: 1, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'lemon-garlic-pangasius-couscous',
    name: 'Lemon garlic pangasius with couscous',
    emoji: '🍋',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 25,
    servings: 2,
    ingredients: [
      { ingredientId: 'pangasius-fillet', amount: 350, unit: 'g' },
      { ingredientId: 'lemon', amount: 1, unit: 'piece' },
      { ingredientId: 'garlic', amount: 2, unit: 'piece' },
      { ingredientId: 'butter', amount: 15, unit: 'g' },
      { ingredientId: 'couscous', amount: 150, unit: 'g' },
      { ingredientId: 'courgette', amount: 1, unit: 'piece' },
      { ingredientId: 'cherry-tomato', amount: 150, unit: 'g' },
      { ingredientId: 'parsley', amount: 10, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'chicken-tray-bake',
    name: 'Chicken & vegetable tray bake',
    emoji: '🍗',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 45,
    servings: 2,
    ingredients: [
      { ingredientId: 'chicken-thigh', amount: 450, unit: 'g' },
      { ingredientId: 'potato', amount: 400, unit: 'g' },
      { ingredientId: 'bell-pepper', amount: 1, unit: 'piece' },
      { ingredientId: 'courgette', amount: 1, unit: 'piece' },
      { ingredientId: 'red-onion', amount: 1, unit: 'piece' },
      { ingredientId: 'garlic', amount: 3, unit: 'piece' },
      { ingredientId: 'paprika', amount: 3, unit: 'g' },
      { ingredientId: 'oregano', amount: 2, unit: 'g' },
      { ingredientId: 'olive-oil', amount: 30, unit: 'ml' },
    ],
    source: 'seed',
  },
  {
    id: 'creamy-chicken-mushroom-pasta',
    name: 'Creamy chicken & mushroom pasta',
    emoji: '🍄',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 30,
    servings: 2,
    ingredients: [
      { ingredientId: 'spaghetti', amount: 200, unit: 'g' },
      { ingredientId: 'chicken-breast', amount: 300, unit: 'g' },
      { ingredientId: 'mushroom', amount: 200, unit: 'g' },
      { ingredientId: 'cooking-cream', amount: 150, unit: 'ml' },
      { ingredientId: 'garlic', amount: 2, unit: 'piece' },
      { ingredientId: 'spinach', amount: 80, unit: 'g' },
      { ingredientId: 'parmesan', amount: 30, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'minestrone',
    name: 'Minestrone with beans',
    emoji: '🥣',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 40,
    servings: 2,
    ingredients: [
      { ingredientId: 'kidney-bean', amount: 200, unit: 'g' },
      { ingredientId: 'macaroni', amount: 60, unit: 'g' },
      { ingredientId: 'tinned-tomato', amount: 400, unit: 'g' },
      { ingredientId: 'carrot', amount: 1, unit: 'piece' },
      { ingredientId: 'courgette', amount: 1, unit: 'piece' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'garlic', amount: 2, unit: 'piece' },
      { ingredientId: 'stock-cube', amount: 1, unit: 'piece' },
      { ingredientId: 'parmesan', amount: 20, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'chicken-avocado-club',
    name: 'Chicken avocado club sandwich',
    emoji: '🥑',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 15,
    servings: 2,
    ingredients: [
      { ingredientId: 'wholegrain-bread', amount: 6, unit: 'piece' },
      { ingredientId: 'sliced-chicken', amount: 150, unit: 'g' },
      { ingredientId: 'avocado', amount: 1, unit: 'piece' },
      { ingredientId: 'egg', amount: 2, unit: 'piece' },
      { ingredientId: 'tomato', amount: 1, unit: 'piece' },
      { ingredientId: 'lettuce', amount: 0.25, unit: 'piece' },
      { ingredientId: 'mayonnaise', amount: 20, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'steak-potatoes-salad',
    name: 'Steak with roast potatoes & salad',
    emoji: '🥩',
    mealTypes: ['Dinner'],
    cuisine: 'international',
    difficulty: 'medium',
    prepMinutes: 40,
    servings: 2,
    ingredients: [
      { ingredientId: 'beef-steak', amount: 400, unit: 'g' },
      { ingredientId: 'potato', amount: 400, unit: 'g' },
      { ingredientId: 'salad-mix', amount: 100, unit: 'g' },
      { ingredientId: 'cherry-tomato', amount: 100, unit: 'g' },
      { ingredientId: 'garlic', amount: 2, unit: 'piece' },
      { ingredientId: 'butter', amount: 20, unit: 'g' },
      { ingredientId: 'olive-oil', amount: 15, unit: 'ml' },
    ],
    source: 'seed',
  },
  {
    id: 'black-bean-burrito-bowl',
    name: 'Black bean & chicken burrito bowl',
    emoji: '🥙',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 30,
    servings: 2,
    ingredients: [
      { ingredientId: 'basmati-rice', amount: 150, unit: 'g' },
      { ingredientId: 'black-bean', amount: 200, unit: 'g' },
      { ingredientId: 'chicken-breast', amount: 250, unit: 'g' },
      { ingredientId: 'sweet-corn', amount: 100, unit: 'g' },
      { ingredientId: 'avocado', amount: 1, unit: 'piece' },
      { ingredientId: 'salsa', amount: 80, unit: 'g' },
      { ingredientId: 'lime', amount: 1, unit: 'piece' },
      { ingredientId: 'taco-seasoning', amount: 10, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'chicken-quesadilla',
    name: 'Chicken quesadilla',
    emoji: '🧀',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 20,
    servings: 2,
    ingredients: [
      { ingredientId: 'tortilla-wrap', amount: 4, unit: 'piece' },
      { ingredientId: 'chicken-breast', amount: 250, unit: 'g' },
      { ingredientId: 'mozzarella', amount: 100, unit: 'g' },
      { ingredientId: 'bell-pepper', amount: 1, unit: 'piece' },
      { ingredientId: 'spring-onion', amount: 2, unit: 'piece' },
      { ingredientId: 'paprika', amount: 2, unit: 'g' },
      { ingredientId: 'salsa', amount: 60, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'greek-chickpea-chicken-salad',
    name: 'Greek chicken & chickpea salad',
    emoji: '🥗',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 20,
    servings: 2,
    ingredients: [
      { ingredientId: 'chicken-breast', amount: 250, unit: 'g' },
      { ingredientId: 'chickpea', amount: 200, unit: 'g' },
      { ingredientId: 'cucumber', amount: 1, unit: 'piece' },
      { ingredientId: 'cherry-tomato', amount: 150, unit: 'g' },
      { ingredientId: 'red-onion', amount: 0.5, unit: 'piece' },
      { ingredientId: 'feta', amount: 80, unit: 'g' },
      { ingredientId: 'oregano', amount: 2, unit: 'g' },
      { ingredientId: 'lemon', amount: 1, unit: 'piece' },
      { ingredientId: 'olive-oil', amount: 20, unit: 'ml' },
    ],
    source: 'seed',
  },
  {
    id: 'flatbread-pizza',
    name: 'Chicken & mushroom flatbread pizza',
    emoji: '🍕',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 20,
    servings: 2,
    ingredients: [
      { ingredientId: 'flatbread', amount: 2, unit: 'piece' },
      { ingredientId: 'tomato-paste', amount: 40, unit: 'g' },
      { ingredientId: 'mozzarella', amount: 125, unit: 'g' },
      { ingredientId: 'sliced-chicken', amount: 100, unit: 'g' },
      { ingredientId: 'mushroom', amount: 100, unit: 'g' },
      { ingredientId: 'bell-pepper', amount: 1, unit: 'piece' },
      { ingredientId: 'oregano', amount: 2, unit: 'g' },
    ],
    source: 'seed',
  },
  {
    id: 'mushroom-soup',
    name: 'Creamy mushroom soup',
    emoji: '🍄',
    mealTypes: ['Dinner'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 30,
    servings: 2,
    ingredients: [
      { ingredientId: 'mushroom', amount: 400, unit: 'g' },
      { ingredientId: 'onion', amount: 1, unit: 'piece' },
      { ingredientId: 'garlic', amount: 2, unit: 'piece' },
      { ingredientId: 'potato', amount: 150, unit: 'g' },
      { ingredientId: 'stock-cube', amount: 1, unit: 'piece' },
      { ingredientId: 'cooking-cream', amount: 100, unit: 'ml' },
      { ingredientId: 'butter', amount: 15, unit: 'g' },
      { ingredientId: 'bread-roll', amount: 2, unit: 'piece' },
    ],
    source: 'seed',
  },
  {
    id: 'shrimp-avocado-salad',
    name: 'Shrimp & avocado salad',
    emoji: '🦐',
    mealTypes: ['Lunch', 'Dinner'],
    cuisine: 'international',
    difficulty: 'easy',
    prepMinutes: 15,
    servings: 2,
    ingredients: [
      { ingredientId: 'shrimp', amount: 250, unit: 'g' },
      { ingredientId: 'avocado', amount: 1, unit: 'piece' },
      { ingredientId: 'salad-mix', amount: 100, unit: 'g' },
      { ingredientId: 'cherry-tomato', amount: 150, unit: 'g' },
      { ingredientId: 'cucumber', amount: 1, unit: 'piece' },
      { ingredientId: 'lime', amount: 1, unit: 'piece' },
      { ingredientId: 'olive-oil', amount: 20, unit: 'ml' },
      { ingredientId: 'garlic', amount: 1, unit: 'piece' },
    ],
    source: 'seed',
  },
]
